Fix broken workflows
Dropped testing from unsupported python versions (3.7 and 3.8, so we only test
on 3.9 - 3.11 for now); also added pyyaml to dev-feisty environment since
github actions were failing with

ModuleNotFoundError: No module named 'yaml'