Fix broken workflows (#59)
* Fix broken workflows

Dropped testing from unsupported python versions (3.7 and 3.8, so we only test
on 3.9 - 3.11 for now); also added pyyaml to dev-feisty environment since
github actions were failing with

ModuleNotFoundError: No module named 'yaml'

* Try using pip to install pyyaml

* Try pinning versions

Pinned everything that gets installed by pip to versions used last time CI ran
successfully

* pip requires ==, not =

* More issues with pip notation

From github, specify version with @ rather than ==

* Move from pip to conda-forge

All the packages we were installing with pip are available on conda-forge now

* fix typo in package name

* pin sphinxcontrib-autoyaml

conda-forge wants to install 0.6.2, which does not build documentation
successfully; last pip install that ran installed 1.1.3